feat(Dialog): All variants use `flex`
iTwin/iTwinUI pull request #1269
Opened 2023-05-10 16:47 UTC by FlyersPh9

## Changes

- `.iui-dialog` has `display: flex;` & `flex-direction: column;` rather than the class modifiers.

Closes #1268.

## Testing

- Ran visual tests.

## Docs

N/A

2023-05-10 18:31 UTC, mayank99 commented on .changeset/thirty-lemons-tie.md
> +All dialog variants have `flex` applied.
```suggestion
All dialog variants have `flex` applied by default. This means the content should be wrapped with `Dialog.Content` or `ModalContent` for optimal layout.
```

2023-05-10 18:36 UTC, FlyersPh9 commented on .changeset/thirty-lemons-tie.md
> +'@itwin/itwinui-css': major
Ok, suggestion applied.

2023-05-10 18:36 UTC, FlyersPh9 commented on .changeset/thirty-lemons-tie.md
> +All dialog variants have `flex` applied.
Ok, suggestion applied.

2023-05-10 18:40 UTC, mayank99 requested changes
LGTM. Lets wait for pending v2 PRs to release (#1250) before merging this.

(Blocking accidental merge using "Request changes".)

2023-05-10 19:07 UTC, mayank99 commented
@FlyersPh9 I vaguely recall there were some hacks we needed to do because `display: flex` was not always present. Think you'll be able to dig through the history and find those?

Here's one I found: https://github.com/iTwin/iTwinUI/pull/1066#issuecomment-1424330775

We might want to make some changes in the dialog code now that we can assume `display: flex` is always present.

2023-05-11 20:33 UTC, FlyersPh9 commented
> @FlyersPh9 I vaguely recall there were some hacks we needed to do because `display: flex` was not always present. Think you'll be able to dig through the history and find those?
> 
> Here's one I found: [#1066 (comment)](https://github.com/iTwin/iTwinUI/pull/1066#issuecomment-1424330775)
> 
> We might want to make some changes in the dialog code now that we can assume `display: flex` is always present.

Done, added a bullet to the PR description with more deets.

2023-05-17 20:58 UTC, merged